---
apiVersion: v1
kind: Namespace
metadata:
  name: infra

---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit
  namespace: infra
spec:
  limits:
  - defaultRequest:
      memory: 10Mi
      cpu: 50m
    type: Container
