---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: libero-reviewer--prod
  namespace: reviewer
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/submission: glob:master-*-*
    filter.fluxcd.io/client: glob:master-*-*
    filter.fluxcd.io/continuumAdaptor: glob:master-*-*

spec:
  releaseName: libero-reviewer--prod
  chart:
    repository: https://libero.github.io/reviewer
    name: libero-reviewer
    version: 0.27.0

  values:
    replicaCount: 1
    ingress:
      enabled: "true"
      host: reviewer--prod-rc.elifesciences.org
      annotations:
        kubernetes.io/ingress.class: nginx

    postgresql:
      existingSecret: libero-reviewer--prod-postgresql

    authenticationJwtSecret: libero-reviewer--prod-auth-jwt

    submission:
      image:
        repository: liberoadmin/reviewer-submission
        tag: master-8181ba81-20200818.1239
      resources:
        requests:
          memory: 300Mi
          cpu: 200m
      sciencebeam:
        convertUrl: "http://sciencebeam--reviewer:8075/api/convert"
      s3:
        secret: libero-reviewer--prod-s3
        bucket: "staging-libero-reviewer"
      meca:
        sftpSecret: libero-reviewer--prod-ejp-sftp
        sftpPath: "/"
        emailPrefix: "[reviewer-production-rc] "
        emailRecipient: "xpub-tech-alerts@elifesciences.org"
        apiSecret: "libero-reviewer--prod-meca-api"
      mail:
        sesSecret: "libero-reviewer--prod-ses"
        sesRegion: "us-east-1"
        sendMail: true
        sender: "prod-rc-noreply@elifesciences.org"
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1

    client:
      image:
        repository: liberoadmin/reviewer-client
        tag: master-e3b0df8d-20200811.1241
      resources:
        requests:
          memory: 50Mi
          cpu: 200m
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1

    continuumAdaptor:
      image:
        repository: liberoadmin/continuum-adaptor
        tag: master-4cc44cb4-20200818.1249
      resources:
        requests:
          memory: 150Mi
          cpu: 200m
      continuumApiUrl: "http://continuumtest--gateway.elife.internal"
      continuumLoginUrl: "https://continuumtest--cdn-journal.elifesciences.org/submit"
      elifeApiSecret: "libero-reviewer--prod-elife-api"
      continuumJwtSecret: "libero-reviewer--prod-continuum-journal-jwt"
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1

    browsertests:
      runPostRelease: false
      testFixture: Minimal
      baseurl: libero-reviewer--prod-client-canary.prod

    newRelic:
      enabled: true
      appName: elife-reviewer--prod
      licenseKeySecret: "libero-reviewer--newrelic-license"
      additionalEnvironmentVariables:
        NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
        NEW_RELIC_ATTRIBUTES_EXCLUDE: >
          'request.headers.cookie',
          'request.headers.authorization',
          'request.headers.proxyAuthorization',
          'request.headers.setCookie*',
          'request.headers.x*',
          'response.headers.cookie',
          'response.headers.authorization',
          'response.headers.proxyAuthorization',
          'response.headers.setCookie*',
          'response.headers.x*'
