apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--prod-ses
  namespace: reviewer
spec:
  encryptedData:
    access-key: AgDAiivHA0A+181hAKcxX3Plis97Pa9LTEGzirbh9qfRdhkwgMn6XWYzvW1EVdwSGQNTNOnFXtt0lLZGXl1UPV97VOuBtXkOEQc5nTSLDl3cY0ZxeAoZlSTaJsryJDxecJ/fgyckH/naD85a1mxoF1cIVO0Ph8qIu3jTFgPHLeGOZC/tKKzc9ZlsPP+oEaweRMf3kQcgzlscQZBsuuBvdVnokb6vWu3UQSEZiivCAMpKD8ggbHvbQocNtICh/x/RaXZoYK5Up7LHMZXZx3j1cuyoz8lHtoAZxR5qO0VJWBB+yUqta7nxwb0bnPiZxmjBzWmtZzg8EjVOhyl666AOR8MQdgvI/ZAgM0LaiGngbt5TraVtegwy2O1Ly3BFOsxZhc/d//u4E992cNaIHYRVt/q2HmKQpkARu38uhoq853my5HQV/yBU9ejPyyNcIkpVN3UDVOI0k1Y0UNeW9uo289nhXeMJCmgeSPpzq6XytZlrHlOVhCOY6YIN/fCNyOlqVBiLbM8jgf6aBn3WFiI8bHn3+6T4lftXkvtaMU+x6DfIBEwW9K0iojmXtztf28Dlrshfv4uNlUrmUn0PuBwOy2CC/7VNq5x7jlcjD3gDM8iLk3LY0S3M47HozkdkWc7xeZwJnkvfboev6j0REIs4fmZjfle1bVYRFOK4CUUV9W9k8V/wBXdFf8RVIe4RDVJst2eJ/cLFcCC3W6peGIrlUKRGlMvhB7jvgtZ3B7ecC5MgMq6cMZf51ZH/
    id: AgCQszKpeqeUXBwCaLyaHNLAnV1ocQEwrTYChZoS2efZhaJpiM2goZ8bS6NwojdvW1wPKmSkPrMSCMDjVn69vpEIEEoJXjBVVYo6WFDnES/F2H9x/o+Zcm5YacpB6M4GPQ1xLLxtd0VfWAQOiJokIwhxJRfT418BW5CkXIq0xxxFa8J6CdROXeJAuRfggiTLOwHyy9Tv9HwVz131f07EolULtpPL2Wzp+q9AbfPIkumSe0TTZGhryyALAMZaCeP7+UxhDCLMIO8MLujdiwfcrjd/8kPc8In7xK13PyaZO7hWSBOzL9o7TTjMNYDiuHcJqcZ+jESVnvnY3bzji8TsgXlUZS5gKYRnBo97VzlQvm8aTMjBN9LJb5DFJHfvLHYJMkgRLu2X5psUOo1POBCEo+cin1zf3cVUIJi5nT10CF0o/dzeQMq3nU49YOiTQVJRvvPGPO8buRsfE85GZfkKWLFm+go+d9gLHgQwVVAEErUVImvoFijrMosGshvZWXpJZXsYiL9oDKV3+D5YjvAA+lV0KzdCNC2930MXcrTREmjFEi1DFVukV4rcdFVTUpPLrU/xZ5ulOFSXAkfBYfunpnm6tQGzIvdlni5KDTQE0haEnTmdZ0LDfKLxA5KngR4mK2lDG/thbgg/27WotazFh9N1pgAHyCNv5R2s0ob9zn7b+qfN+pU3gU/IZ4gLqvWd2Pmctgy8UNne4rMnv7lvGExsUoRzAQ==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--prod-ses
      namespace: reviewer
    type: Opaque

