apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--stg-continuum-journal-jwt
  namespace: reviewer
spec:
  encryptedData:
    continuumJwtSecret: AgAT1ewMjdc8D7udel10Kc3FkLOfuV8/lkARTa9QaGB9N4tXqf/jlN+Xjr5V+9YPJaJQLv/EmN3FuvM4W7LTtNMAXfR3kpvduRBSIeXOYmWmKcwOSFcugk9n4D2MwTMv740Zs8rZfVUxujw7DUrwfbHabD79jm3gi9cUFg4LvnJ/dQLck/Kgu4FHt178s/k+7Ka498gahH9Vd9DgW6PXj4pnxoVcrc1PGhs0ZO8oQN9gmtpWYP/1WDeZY+Kv1mqdxKWZmL77WCR/HGO6nB+jByJBabNgw+qu5nvHhFLchapKOQs2vsZuhsBBtUPnbEUVEgs3dEzwiPxTB40SsVsLHPFYGc5NKq5QM8UOar2aQ2j2EzQWrM38p9JoZcUbmKDFdQbe4nfrDRW4YTgeoQqFoUPuPHb+vakrEwKfgSI2oaIVJzR59VwXmqU9spMtIndNYLxCO4ar7dCQqlCYmAo3jEb/DU4MnutO+LFNJMYLTcDeekh6ZASz7GxaWuLNn1kCnBWEWlN4ojc5z7s+mzQl2SqbmgJq6XGTDpCYrNxNMtvWhJU6aWj/dYJ86XgPo5Yci0GbyvSyE9CMtUf/fz0LAfEsJQ7JeHYmf7yHuBKRDQzZQtu+V2FUZvhz8OsFxD9WjrP1ZN+6BJixLzJmqzTuS8qgUGjtcFhhiRlLQ5zw33X/VIlae3SbF7I2UR4naxm5zuSDtn9mYPr6/CveKz2302O9uaAZYlSk9ZIgm+Y9edOjUg==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--stg-continuum-journal-jwt
      namespace: reviewer
    type: Opaque

