apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--stg-postgresql
  namespace: reviewer
spec:
  encryptedData:
    postgresql-password: AgAwrFqnyFBEEYUz+lqen6tKDAFly0ZqEhfGr3e4EifI0rif6yDTaO486f4DDHkwK1hcvhN9F/ZPs1u/4fnxuK/eB9ZNW6As/l4LyV+e64KrqHc4KGIKFsnBn3Jc97ucJLorVZ66VwnDSeOaHSYrfRX66r2BFDvv66Bc6jl7O8OroozGEtpU2D8OPFDshnamyWO6VQmoEO4jJrollLC+s7t3lNXc5YxPDwjoFnumpegdK1Z72Y5XbnZOPfQFBCnwrxQS3HvfNAEWn49b/68zDmtCsvXyak66TMSdN2JOXSUb0pacvykY53S5dB8qIBHZw+8xWvhI14wGohSUzGg9f2VZg8Y55kNb9ot8M6Vhk+Jez/tQHTapNq2+fyrsxrTXFQQswOFWPoGTkJB6HJzJ/qujj2N3xlfdSifRKjeLiisa8KK+gZ6b0cMblqUvhyK+UX6K2/Wvn6ltFcSbStkHx/lcfxLxgT9Opgcatf9cz2jqGQirNg1/VcCZgn3IRMeNFXfoTSmTQIzvQIaOk/bo8DOzI9RnN9B6B0qEYlxaBCwBdDsV3e5xWrcTNgpl94teitxdNk475mlyf18ALfXGL5UMF+K4xsXY8oqV1XCkxoylJ5oMRFLa6NP4SS089HylgsRLF7vq4QxvIzaZm9w/zwc+EFrCUR4ghZlNh8cBHaGCm9ptlaEY1FGEOvhzDjx//hrbEJgZn0EOaM/0lwQorClH1U8TRSbU+siG4CEYvKLO6w==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--stg-postgresql
      namespace: reviewer
    type: Opaque

