apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--prod-continuum-journal-jwt
  namespace: prod
spec:
  encryptedData:
    continuumJwtSecret: AgBgaSYbiX2RmGqMAV0c2BDs2ija8UsjiYBZ2ua72/NfGuo/6imG40TF9ZvCJ7E123mUs9CF8U/qtz3n3SSB4CErGEavwOABabMrUFdMOQSU0CWu81Z6+mWgn32hfCeu0FlB86y8jJf1fMzqw1p9BM0PaPXi8sVbnfQogJYITqZsvFhyW4hFJ0QHvmTf5uhFJ0nutuzDsw2bCLqJm+3HLFAZwsTD7bDIbHdfQURcFw60N3M+3M+HL1YWMjbZX+NTUjOqqR/5VRsp2IejO6ombS/TjlJxxOB5A/5ANJXZwLHhNIvoRRM+C85EILe3bonnxD8gm+vhw3ZofzTMX7xHiKBaTOstudbGb0iU6LYvXE4agVj+ASp881wBK/Abl9FfEGeN89nsOEGQ8Djc93qDXYeqM8d4oK8S4PzcQBVDTJbgDg6OBLIbKTe/WorcyVyBlQr5avCfOhtjRkSkFtu4wESIsX3ppU6FkTZeS6fdmPpbOLbbEfFGdtX24wT96PzErcFCgQZQgEnnlp4F5jsP2ALS4hJqCaxsGbVlxOe65gwbbOgdnvdoiWG1sCdl3Pt5BGGDcvD7XBmL0Xv50rYlpQTv3KUTjWt4knc7HLhFWaAU/etAjIOGKyM6ecnjqS0BdtMxr5wrXpvknPvW/M+GHKMi4y9qvXtQylrDUdXlQZB943P1ZVzq/Kj2EJFBcaAUpba1ogFnVP+Zmp5nRJu9e96PyQ86zAtRDPE1hQbwwpc0Aw==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--prod-continuum-journal-jwt
      namespace: prod
    type: Opaque

