apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--stg-s3
  namespace: reviewer
spec:
  encryptedData:
    access-key: AgAXyRu8PoWlOa9pzAajJifmUehtvBym4zbY7a45M0kLl7F4LyemqyB+G63Zs6saxtBEWkjtRv+ocIVjQYVAw5oUW3TtEDc9ZDBm/2IwgRrNqI6Rb0TuLaN2nngDrc6fdwc11FVWJIA+LBQIzhZUkr8AquCD9Zzo80mrODUQunJD7mNTVen0WAyqot5xeXxsLYGOOVudfkzOCM+S/QrZQDBlne3LYG7TZNGV2SjofksfgGvkrGSUGZtPqHa39X8izNcB6DbT/+5UR7JF3xfArFFlUafvzX0CkcwfnxaxL/95cpgMLl5kYVl6/nju7TjIo6nRDs8PcR3aa7pEsK6fz4eNtvRZzkIYJxsI2snHWVJZJrJqb2xF7h76MF8iJ3JEzJKzo8Ru1Gr/UXIDP/MP39YQR2VRKB2QQ45HQKY7NybP+R2mIdWw1K1ag3yHYuIR7AlKIFBtYulrWT/vmMlHOOqkzFjvLZOaaOJUaF+LbrqmCaqaPqFxD1a5wtKXRunvnasz2nxeAPtDJOjp+Vm5q/fa33HsVocRoGVq/5ia44bX3F73MFpRSi09b/QF5enmmsKdLh2GqMdkFfSDLUSyiwXZ38udO2dlu9em5oyQ2OC2wr19C+qqkNsQAwQCmbGWPkEvAkXMnV3owvqUUhNJJfqS+SaeP1W3nLpwWZinHqZxdDacWeGmPlffzDjkrrUu6C/A7MdE+obSSOyUp6pR0QvFHuMVNu2+gPSWxWuRN9o9eUmvgTnstMac
    id: AgA2u06nbkbZWUx8pBOoUaqvGAb+3ZuWqahGHtz3DZNrw+vFi7TGEmo0PQnPhgT8W4anVkTDAbm+OOo5Ti/u7I6+I9pSzmw3y1apRUjUiLtdUi4f8Puq/X0MXvKRThbOM3ZdLSCvtewvL8NV8QO7kNetLZ1IYryFjafJ37R7MhTEAqGmW5seLIsr9QAe8S8SyHcDijwL8/tkoOVDz0YM6W864RFn8ZVr3toxnFaPvwrGFO5fhFgVtLsegIxgY5X1QETV1xVaPwXlNhjh5c6lvgN3S4DGXHPMxtEVZ8/en8gJMVpI60JpoMEmPw6BhY+rca4CiBB+xjKMCwVb1C3am4+N0to7nZnS23crkU4oakNtG5YJ1Ts5V1X/LdHei0vgfvQ2/I4QYmXdgNqqV/1+tVTfzigZw3vAnlzhhZSf95zdforD3Pkn/xjQEmIogE0TV+ygu8oi8D3Lc/YJtGNtyh83SMeWEsIflVwjBNspQdd5JLzlBZLWXOuf+GWUJuxNdMM6tOfc5sDK/bWN0CXeORb9L3IwAtxAlP4gNm2G6/i7c/OXfLoQEE4XPkUIZho54JPAeeZcvDeK32niW2cj1X1UxgnO3ABDQ1sU++mEFCT4+mBj9s3g/EU9GiP53BeAH3pj1qUO/VsLV5ZfzSS2U0YJZTrA9/M36g1ujIlmg8o4fRVsaPnsSspMC0DjebSOnQ9LhIEyz/XDJSBfZSu/Nu1pnlwTvA==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--stg-s3
      namespace: reviewer
    type: Opaque

