apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--prod-s3
  namespace: prod
spec:
  encryptedData:
    access-key: AgAcZMjeoHF5pNFO4phczl06/BHunW5brSK9l4st+Q7KRUCxXWHSr14yEeDDVtPQSF3TvrAb7joZVoUCrR0AnzG5sw7mEs9KgTfOIZA0EY61g6izyilQu1+BPurTq8phA58K3GeWX0UjkEhUWzFlUwDc6E+vadH8zQ8s7eedkRwSfABJxEBO6Ri83MIoeGnuRBKkrEFuMQgdIUhRKF4VaoNBknNUCy21/Tqvci96L5ucU9XI7XBg5bfX3yJuXGOS+5cXLQ3/XnWgqmv5WKmD9W3QKmdb4lip/ovrFw0TjRafYp/RfAR37bb9haCiVb/GDJo2c+lnOQihGj8dLygUQsnbmhCnUIf//G6QMDRzOiHj7Iz7U6PRCIrM5b01fh69Mz2TYswYodoWdCVnDCc/PLLmLw1yLjDIVRl1KJkHYqJq+K30Rz/6eKP62CXVvxaN/0lDxDhIeByJcLs2WehLHzECMY7NtFX+5Cpjvf+unvO0ntXLcN4+O4xghUDWrue7DKbgVCcRK+xqcYpIYnJoBsW+YA8LGYuXqgAga/k2gt62JmcmB5wM8vVGlF0t83pfz7sxwUy4/41onibHj4WjGXt6HL9EHwgMNb/83Br/46NrJ75MMUGLfQDjGyZ9L6c3takFZ006tx5T4HNO59kVZDDDg+blSq0BTYUbOuG4RtZvhjJ+8vtJUp8I8qePn8o74VLEcQST/XhjiPx4rqv2HrZ8qWg/1YPMXiwbMWxPvIEQ22piOD5zVH6T
    id: AgCoCMxODT9IiMlPknbSGooHaerm1EYcYlCinl+FUuoFXj5NOixkKJApCHwYgIy9LT5w7pFymynqcuEehQRNR8q1PhbqP/kE5dWB9xXxtJFz9xvGEYRHXufZLmJan2saf8Jk9buKW1E+TmqvCOUEJQF75+YOiehmGofw0z2bO2e9K4UnYAU6fmSx1tH5YiVHfV5ltZt02pTqhZ+WhCl6ALHHUnAXynrHPPHZ1f0oZNyD/tgtP9NekZVB8sV8HcpO+8vVi4HI/2cej8SNiUazOx76qaTDs0JFAad+4CzXHtLxfHMSbIQyHFqKhc5RBTzt3sVeWCV80Wk26RXBi7bKyXnPElUsQvbFpG8XBoDS/zpg7UoFS37bO3Eww18QcQMqCoRQgAPPYRWUUyBfBq7VbFg4+N6pC7w4fqOrzwfhU83Mw855kROYJ2uoThNfOft0/YXdTyAU/apzVR1PE+Z1VQYdHiuMh8Sv69lvw2Usp+ZmAjaSINXjB39SvWOsZxjvoGzV4+s7XDAxgWlEgBh+ZVxNgb9lFFtc25+3TdW/8M5IQmF44FmVaNMHFpZlQJ+gaTMNWxuRIDrFhDH8tpqO0ycIjiBdO6LmOWmrExwREKa77buWI6r0oFb6zgczU+6RPnUdwJXYyhCyZwFI0C11XHFy22etiLqJen6zIcauBs/3H27Ogll+bRTK5cC7EojNj9MWaEwcDy33QUw+OUhgcTkkQ4/Mog==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--prod-s3
      namespace: prod
    type: Opaque

