apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--prod-ses
  namespace: reviewer
spec:
  encryptedData:
    access-key: AgAw/sa4XW+vFdd9i6PnzZErsOQYGD3rGcNE2VMyFKUAq8FhhRVJm50pFbh+M9GqwVGbM6VvAaeWi254Gb1Nz+rmk3lxXYO5uDBq+awxhem9h1WTaYP2Yxd5osrkio92XZoWrX9h4qoqk8Qz12dkNwiG4yQgpv0gcRWN7RvTMUhlHUlVJyY6CZnS3XRhgQB8yQsKrW8BQ897uCUHSVlCP+QGEakzRPNnB5WIUnDzOn0aX2eE7OA2nCsWADzKJ4dQYMS3Jvisnz67d4BsLah5Qmnkes9skTP2z0t8IVGPXOPSYo4+1X495ZwVR+Pgg43Q+6OiTV/atd5fo7Ji4Zbjlkz0MvBOBkEFXfbSFOiToHO1eJcXOyjoeb4jBFX1hoAgfF8LoUo3Aor9T1XULVFt+IOA4n/gQPkCjisgBY8qTcKukivlgAMbpXRIQB2IYl+ygb6GQhCYBVL1GigfopZDb85qSMxlCCLFDb7HPZ4+TiUu3i1xHjnAu63puC845aBMEBLRPvKrRaMVNwVcEp8LWjWITbwI1k9C4wBRVeLXF7Pz/4O4RVubpm6IdyWKPjWRgVGiUvBe0p69HNdvKzhtW+7lNXLHXt7aTqGp2a2BFQOIF2tq/Es00Xvj58lK+KW1r44xxxugGLuv7Z4P9R+GnZAHVvMelURieYzFvZAVD/r8HMlzcHlsBh2XoLMwwnbYWFwM4mBXslG3csoN5QoCn8ooUHQWSnA5ENZ702nKMKzeMyMIIKTXgHqw
    id: AgBer4DtFcQWx3hQyLOG2zlYKibBMtH8mkzA7hEHIFFeY7JPvxvrd3xcc6WqdK4qKt/Ei8IL0gtYLiHJaz32yyuPJX7162yE1DOhKGGC//mFkZfapL6qNfdfxIR5++SN8YXOW9/WqbLWM/z6Di7POX5LQYGpMEvmoPKpkkfzZ0dRfUanomz9JDkUN4MgnmkWF6c7HXNxujxSgCKlfNFQ/mu7FcVyk7TpW6KcteRO7zAgR0lwDB8cd42BA3RHcklas6UpqoAbgu994BDy8pYwfcwlEfWYR+C6kSDp58QjVc3QDrZsiOxZAFYWJnTIiDkWPncPXu0S/pvCkCRZyySpRRomjQACnzPQTWLL6nyepTGmjkA9eqaP/wHqciuRcC2fNGu6/yHZQQjUd43qoF1hvozPqPuvaVau1ni+ql+a+bfDjJlplFIqiP99idbx/E/V8GERaeNagpeqAWOrT0SJhjStotgqdMqyCjLzQSkeFFLKV9KsJNeU20oJh7SsHRYs3Bqo45VqF3y8jgkZ+o8RWYs0x4cs+z8/B+1sc/V1R9rPQjKFastcyh/BOka3EVe6umeDSFKErN5adgD6+RWd3yCZpPmr/CGieREEt9gZFen6um8lc6GnffX8O8oitLUI9zBDpQHGKgc9/rqkf0lzwZNxeq+svy4x+6dBZ7JTGsXRU08hT20nGcqjYgO9VclqTAPVKOx+5X1mUdLSijKE3SWFjoWf/Q==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--prod-ses
      namespace: reviewer
    type: Opaque

