apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--stg-meca-api
  namespace: reviewer
spec:
  encryptedData:
    key: AgAuLr7xgC3fPnKfV35S+HJRTIFBKo/YYqEiYVMObRWJjsIRP3xAVBBC8q2a+bIXOFFUqZ0QjnALnR9NYLb9nbk7Ge5cXtKjUQu74LJ9dyW0xX/1QrPZiUO8wFfP9HQxQrLceHZsj/O5Fl8HpHYR2T0N/xzPFzMQtjvZHkk2yB3pxWTdp2o7PyIZq5Va8fkvc0hhB6F8orli8JR9sKmzOJPAQhY+Ch348/zFgXx9+gKad79UWmwWi8I26tvzjzmq+Uy2VgKsqlXwrtJJe9yPj9wA/giuZbbaarDPFLZ4fqGAkxGP74eTbihq26Hy1SlG7jAc5y6Xz1zgTlx1CMcUW5w2jnoZTiFHcJTTbS9IhwfvqMpqWO4ILt8sALoBuWmrI2cApAi62el8MKE3xgfztNltBK9BkN3x3zqxxXeFUF0fpTOviuXFSvOqzIi+NbqSdKz3GooaboDk3tUxUd7KaNur7V8lvyqBlKYgHxNA3BEwXcWsF0dm13oehA0Emev3k7Etk08HY35pAyXFxjpJDUVW3GN8icMmItIrPRnRkkw7cfUnOb6RJqbNGJVTn0IW0KlIdVfGauNmvPL9Fs+qyJuKo2bbPc4IWQuOV5r9FDcBZZR12nIE/htyGnzKr4SzVXCS/Sv79+YHcX2VOntytlMO58n/IsPfz9ZhXd3uSS9hY6mXbvE2ho2OdyBDD+07F3/c3rdE3sMFQ259JVhzxkErNAh7QjmcqEi5Rej/y4tR/g==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--stg-meca-api
      namespace: reviewer
    type: Opaque

