apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--prod-continuum-journal-jwt
  namespace: reviewer
spec:
  encryptedData:
    continuumJwtSecret: AgBuw176DxcFFE857l1D8TBAg/oufVClVnXveSjM96Wx36b+WnZlP8RbCuXJZNm0BnMDgZ/9D4ISDJKPGh2iWiAR7NDd8OvevPHP88APVbKp2dT4IMqFmvVJdlsfmBBb9W0AZ1Qby0UocK/jUlvpXSYpu66MPB9FMi8SbhacvcGeSP8VBAjHjd02Ovhlz/YsI+13yRKW/l6boWtyycDecePvMHhNqI3f3iX4itWYdbvU8HKw9dmmhEBpBBnZGiHKVl5KTVlRyZGmWgWbchdjUwYQg0oH8T7t11GijEzZRZcR2Y7jGz9YK6nIa8imYKsdIE7L//pMfdI6D55r26q6D/rKFFHKUSixEP5aNxuKjiqyPdIcPBf2nFt8cbukwKxPb+ioLv3IsVjPPpZ62zXMfu/o9WXboqiWjiIeUGuyFukHXrPgsvr9SFcDTI3qvkwXYfnY6a3SLvbX44vVujGaN8k+lDB0IqWEs8/bFJYcseQnvXHBlXjy7gbzod+8BdssdjnIvR/Emr/jb9INADlE3mm1il7BAthKe3/vacX36N8N+dBZCJd3TqVW4lLM+wq8xtXiZ2Rj1QMrAf4dgU79T1Y8L08ddvoTN1A5YzjyQKWcBo9Hxut2/DiUm2lpwJyhDya8v2OuG2UBP6Kqt/3xrn/L0NzaVYaIUFlINXYQZbV4Xud0Npm5j7V9MsrLGQszYDLpMgZGh7cAOVaLlloDE9VGQtVaa8WTQxvPrl9nxSfjsQ==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--prod-continuum-journal-jwt
      namespace: reviewer
    type: Opaque

