apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--stg-continuum-journal-jwt
  namespace: reviewer
spec:
  encryptedData:
    continuumJwtSecret: AgB9uqhHKQl9AFmS1cxiUfwFVkZ4VYPUBv2utjZ5JSZaqe/39L7dlj5g1D/kpEOfxf7Q/wFT0Kx4CnTVCgE2UTgmb5d0TbcmfoKpnWxhT8Oj22a1YoUuNob7x0GHkj0nXEvez6AWC5j8KA6JLIH/AHrUNZS00ljbZMbXnsQ9d0txi6XtgeMKtWgCSLCx71mpIam8cY/ikFg7McOu0Mys56NGrXyiwid2VW8X0oHDi26XLqBG4X4BswYoDch21cWN02P3PnTrVKd43yNCM8yXA+PRwMAd+vVaTQQrEz/oMTDryDzNdG0CYKmmzFuf0/4QjVciyeP0EEinUfgIEuE2YKnN2dqbICokOGopd4Zjz1GJvaWmQsEyJvB1Fgo5z2i/AYg7lUewkSZBC4EznGq+7akVvsI3Cl9F8ej3z8vxvJ8EYuqyUdJl99nG1WAh2IcPmVEwP1aS8V8FoeRvcSLhJjDBLfznVi/Jfel9lYOOMDE2pSK0dFVEfkRdwiRy7hCdzkVJureiHG6Z0TrSfQTiC33S3D0n/bf1WHRAHQM2t6fpLHLn85bw7PN/zs4xVJSH5AFUXui9arJ27MRrz2x5j2DZlGlxB1rPZrpWSQQNVwUYc0VkEW3YWVBMLSQnIpwlf9waUp5/Pwm1nMIRLcUB0Fm90Erdt6ATu01+n3n0JlHQCPWmpG31W9EgXTgASO5vx1xe/HbU+K70zh93zPM5ukWop2Y5swbwDY7elv/VVORyrQ==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--stg-continuum-journal-jwt
      namespace: reviewer
    type: Opaque

