apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: libero-reviewer--prod-s3
  namespace: reviewer
spec:
  encryptedData:
    access-key: AgC6lHkvNquCTRrD2ZaK7f+7sO/NPnP2gi6K8O/sXiBK7GzX+aaYVBwmcNsOyFAyhEPEkfh0rC7vWTeteKBTEc9aIusi5pXoO50OH+nU+EY/txne8lTlkZxSXP1MUsQyJQVzUzivFy6rexFbY1x5nLFuKMF8aRt7hjFkAC+JxUw5c6JqfJ4FhQkhi2z8HzxFKYRqRunV0FaEBRCtm3nk5MUmYGeD0spQihy7nEJXZxNfVQITT0RQJrNi8bN9OZYybtfsntkSsb9o9wu8PhQGEKkR84Q0K71Fo4gd4VwVQycup5b7sD5GVnBOiS/CFO3OXDMIlmlHiuBc0ZLlfbnBUd+EWjq97RoEpdcimzpGxn/OIXzH/FadA584TLdLatcFsnHfrIQS+0rxhh+LJOhg+HS0wtIdkKVMtM4l3Giqxf5ehcELhmQcrLi5/dyEYKZQYv1B95t3Cl0GnJef3D/+2ohmc1epIdaEckn9d4O3/qwf/jF6YRI54883fkeADnUywJU0zyvW+y2C7U3sPzpn7v/bIINe5TB9dev4YC5DhCAPluLvLxqJIRSGlwi3rNOtub5ViCogc0ix5oar9yPcNK20XiVa42c7qbSy3vumuS2vH9gn+Ywpe1YyXjZRNRkdvBDBHHlAAx7xzziZ1Z3UqFvHr88asFHicETFsmtggtA4kvMsJK5tpGCupCa3Jp2VMlv0fAbvelAhyhxaMCCioUYC+y7bQUmwMvJmGuhkGkdN4r7KWrdzgl1c
    id: AgBx1h6r6J/1U2Nmme6381tNLx1hp2u2OA3fMumPd6pxRcmeCtux3KehNF2OEuxqCgT2RihifpGOFr70YaZjsc+cSx6hJTJ1IKoUAUfWEi0IvUE/GpIA0DOMKsKlCZF7FWsGh8C3OCl4AJ+hJe+OcQST2E8SLS8xDjklXZQvh5ZeP/vIKnJmwZdD0UsDfs7Ootxjj9SYAOI/kDMEwn2EzIJiW3qFR5S1XkKgm035suQ/wAJwkLfUMmWV463IanJyOj+A6KjNqxFRQ6SNyrdEd/RJMV3JNIAF0QQm+1ygYNKWmmNb15qmd+fIHGopLPH29Gjf5Qx9tXBIp2EBoiBs57bRJJe8wTPapHns8Q9h/Nmr+1HehZVLEnHQAqU3dnNfg9dGSXYkuRGf+v0LKR0WaoHsYEZzQIYv12xuE4m3JcZLxpq8Hmtzx4P8uSX2QsXp/Sv0u7kOOR9eCKsOKaUppi8A198jOhOQNHpGo86iQ/3OJnQKqn/6YdxoxEp0TiCyATPwTFfamM5wNXQno40W9gpQl/6OCx8Y0WU5IrIvnmLg9Nalp6u3XudlrMj0qriFC+a3+nZQF3U708bRhRWTf0sXWOUhVoXV7Y4y/ECtSNHj4zJosufPP1wqlfmENU2zyUpj2AbQXuq4Q6ok+7wgPAcsuDNa7pgdSM4qyGCsf3dlXONa0k89wYk3He3+y4hdoQ8Em+/6X7GC78mIxMX5Vux9EPOR4w==
  template:
    metadata:
      creationTimestamp: null
      name: libero-reviewer--prod-s3
      namespace: reviewer
    type: Opaque

